### ISSUE TITLE
Undefined index: Authorization in /home/www/dyndns/update.php on line 13

### ISSUE THREAD

**Issue by ner00** [raceybe/cpanel-ddns#3]
I have a small issue with this and I think I need some help to troubleshoot it.
The script works great in almost anyway I tried, except with my Draytek router **when using https**.

http works fine though, curl request works fine too, but with my router it won't work when I select https protocol and logs the error in the title to error_log on the server `Undefined index: Authorization in /home/www/dyndns/update.php on line 13` - [line 13](https://github.com/raceybe/cpanel-ddns/blob/4471659b12c9aff175b318ce239c0235424da2a4/update.php#L13)

The same error is logged in error_log if I access the web page from the browser without any auth parameters.

Here's a screenshot of the config:

![ddns in Draytek router](https://i.imgur.com/BZnxyhu.png)

By just changing the connection type from http to https the error is logged and the update fails.

Any clue how I could debug this?

Thank you!

P.S: I'm wondering if https cannot be used with Basic Auth and maybe I must change from Basic auth to URL (like curl) along these lines: https://superuser.com/a/1545384

**Comment by ner00** [comment]
A quick test using hardcoded plaintext credentials as parameters in the url worked with https on the router.

```
$requestUser = $_GET['usr'];
$requestPassword = $_GET['pwd'];
```
`/update?hostname=host.domain.com&usr=myuser&mypassword=4vM1YDTduA0ut&myip=127.0.0.1"`

I need a better way to test why it won't work with Basic Auth + SSL.

**Comment by ner00** [comment]
A quick test using hardcoded plaintext credentials as parameters in the url worked with https on the router.

```
$requestUser = $_GET['usr'];
$requestPassword = $_GET['pwd'];
```
`/update?hostname=host.domain.com&usr=myuser&pwd=mypassword&myip=###IP###`

I need a better way to test why it won't work with Basic Auth + SSL.

**Comment by raceybe** [comment]
Sorry for the delay. I'll need to look at and think about what the limitations to your application actually are. Supplying credentials in a GET request is insecure, even over HTTPS. what you COULD do, and what I'm actually doing right now for my own use with another person is creating a unique URL similar to the test client. Simply hitting that URL will update with the credentials provided in the PHP file.

I can show an example when I get mine working.

**Comment by raceybe** [comment]
Okay, I have an update. While scripting I noticed that the request probably isn't being made properly if you get the
`Undefined index: Authorization in /home/www/dyndns/update.php on line 13`
We can fix this by fixing the request. To do this, we need to issue the correct CURL command or fix something else.

in the short term you can try the preconfigured URL approach I just uploaded. It isn't perfect security, but it should work in the short term.

As far as working with your specific router, I'm interested in looking at the options you have available...does it use ddclient under the hood?

**Comment by ner00** [comment]
> Supplying credentials in a GET request is insecure, even over HTTPS. what you COULD do, and what I'm actually doing right now for my own use with another person is creating a unique URL similar to the test client.

Thanks for supplying that script, I might use that approach in the future although it introduces a lot of rigidity to the process.
At the moment I don't really mind using the GET parameters in the URL, mainly because their only purpose it to match a hostname using a user/password combination, nothing sensitive about them.

> As far as working with your specific router, I'm interested in looking at the options you have available...does it use ddclient under the hood?

That's a good question. I don't think it uses ddclient, but I also am not sure what it uses. The only thing I can see is the config file when I backup the router configuration, and goes something like this:

```
config 'profile' 'ddns1'
	option 'uciid' '1'
	option 'ifname' 'wan1'
	option 'policy' 'first'
	option 'wild_card' 'disable'
	option 'backup_mx' 'disable'
	option 'mail_extender' ''
	option 'isShow' 'true'
	option 'acme' '0'
	option 'last' ''
	option 'rfilter' 'isShow'
	option 'rvalue' 'true'
	option 'provider' 'CUSTOMIZED'
	option 'provider_host' 'ddns.domain.com'
	option 'auth_type' 'basic'
	option 'login_name' 'myuser'
	option 'login_pw' 'mypassword'
	option 'ip_source' '0'
	option 'time_interval' '1'
	option 'exp_date' ''
	option 'domain_name' 'host.domain.com'
	option 'server_resp' 'good'
	option 'server_type' 'dynamic'
	option 'service_api' '/update?hostname=host.domain.com&myip=###IP###'
	option 'connection_type' 'https'
	option 'status' 'enable'
	option 'force_update' '0'
```

**Comment by raceybe** [comment]
Do you have a valid certificate for https for your server hosting this script? I’m not sure of the behaviour of the certificate is not valid.

**Comment by ner00** [comment]
Yes, the certificate on the server is valid. I think this might just be a bug with the router, although I'm not sure how the request changes between plain http and https.

**Comment by raceybe** [comment]
> 
> 
> Yes, the certificate on the server is valid. I think this might just be a bug with the router, although I'm not sure how the request changes between plain http and https.

what options are available under "Service Provider" and "Service Type"? My code expects "dyndns2" protocol, so maybe you need to correct something in that selection.

**Comment by ner00** [comment]
> what options are available under "Service Provider" and "Service Type"? My code expects "dyndns2" protocol, so maybe you need to correct something in that selection.

I assume it uses dyndns2, because it works fine in http mode. Service provider lists a dozen ddns providers, dyndns, no-ip, etc. Service type has 3 options, dynamic, static, custom. Selecting any of the doesn't seem to allow access to further options, I'm unsure what it is used for. Using http it works with dynamic out of the box.

**Comment by raceybe** [comment]
Hmm, is your cPanel using Apache or Lightspeed for the web server or something else? The code uses

`
$requestAuthString = apache_request_headers()['Authorization'];
`
so when https is selected this header appears to not be present. Maybe you can dump the entire apache_request_headers() variable to see how it differs between http and https?

**Comment by ner00** [comment]
Apparently the router uses wget (at least for https) and doesn't use Basic Auth at all in https mode, so it is a bug that can only be worked around with the URL solution. 

Here's an example of the current behavior:

**Draytek DDNS client (http)**
```
Array
(
    [Host] => ddns.domain.com
    [X-Real-IP] => _host-public-ip_
    [X-Forwarded-By] => _ddns-server-ip_:80
    [Connection] => close
    [Authorization] => Basic _HASH_
    [Content-Type] => application/x-www-form-urlencoded
    [Cache-Control] => no-cache
    [User-Agent] => Vigor2960 series
    [Content-Length] => 0
)
```


**Draytek DDNS client (https)**
```
Array
(
    [Host] => ddns.domain.com
    [X-Real-IP] => _host-public-ip_
    [X-Forwarded-By] => _ddns-server-ip_:443
    [X-Forwarded-Port] => 443
    [X-Forwarded-Proto] => https
    [Connection] => close
    [User-Agent] => Wget/1.16 (linux-gnu)
    [Accept] => */*
    [Content-Length] => 0
)
```

**Comment by raceybe** [comment]
Indeed it does seem like a bug. That's a really weird bug. Why should it matter http or https? Oh well, have any suggestions for alternative work around I can help with?

**Comment by ner00** [comment]
> Oh well, have any suggestions for alternative work around I can help with?

Not really, no, I think there are already quite a few acceptable alternatives to basic auth. In any case, I'm happy with the way it is, this was just one of those minor nuisances that I wanted to try to figure out if I was doing something wrong which apparently wasn't the case.

Thanks for all the suggestions, and mainly the development of the core script itself, it's extremely useful.

**Comment by raceybe** [comment]
as an alternative you might consider looking at https://www.dnsomatic.com/ . I used them for a bit when I did ddns through Google and somewhere else. dnsomatic can be configured to look like dyndns2 protocol, so you could try that one and see if you have different results.
